# -*- coding: utf-8 -*-
"""Rand_Songs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16Ly8HQWrKqKwS8vR_jk-bN5Pi35R9YPu
"""

import pandas as pd
import random

def get_random_songs(num_songs=2000):

    #Insert the file path
    df = pd.read_csv(file_path)

    total_songs = len(df)

    #Generate a list of 2000 random indices from the DataFrame
    random_indices = random.sample(range(total_songs), num_songs)

    #Get the data of the 2000 random songs
    random_songs_data = df.iloc[random_indices]

    return random_songs_data


#Get random songs from the CSV file
random_songs = get_random_songs(csv_file_path)

#Save the randomly selected songs to a new CSV file called "rand_lyrics.csv"
random_songs.to_csv("rand_lyrics.csv", index=False)

#Display the data of the randomly selected songs
print(random_songs)